version: 2
updates:
  - package-ecosystem: cargo
    directory: /app/hook-client
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
